<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="coroco" >
    <xacro:arg name="robot_namespace" default="/" />
    <xacro:arg name="urdf_extras" default="empty.urdf" />

    <xacro:include filename="$(find coroco_description)/urdf/coroco_wheel.xacro" />

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6500" />
    <xacro:property name="base_y_size" value="0.4400" />
    <xacro:property name="base_z_size" value="0.3100" />

    <xacro:property name="wheelbase" value="0.5000" />
    <xacro:property name="track" value="0.4600" />
    <xacro:property name="wheel_vertical_offset" value="-0.1700" />

    <xacro:property name="wheel_length" value="0.1150" />
    <xacro:property name="wheel_radius" value="0.1750" />

    <!-- static transform between /odom and /base_link -->
    <link name="odom"/>
    <joint name="odom_to_base_link=" type="fixed">
        <origin xyz="0 0 ${-wheel_vertical_offset + wheel_radius}" rpy="0 0 0" />
        <parent link="odom"/>
        <child link="base_link"/>
    </joint>

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://coroco_description/meshes/base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.008" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <mass value="50" />
            <!-- <origin xyz="-0.00065 -0.085 0.062" />
            <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" /> -->
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- For testing, hang the robot up in the air -->
    <!-- <link name="world" />
    <joint name="world_to_base_link=" type="fixed">
        <origin xyz="0 0 0.5" rpy="0 0 0" />
        <parent link="world"/>
        <child link="base_link"/>
    </joint> -->

    <!-- coroco wheel macros -->
    <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
    <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
    <xacro:coroco_wheel wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:coroco_wheel>
    <xacro:coroco_wheel wheel_prefix="front_left">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:coroco_wheel>
    <xacro:coroco_wheel wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:coroco_wheel>
    <xacro:coroco_wheel wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:coroco_wheel>

    <link name="front_mount" />

    <joint name="front_mount_joint" type="fixed">
        <origin xyz="0.325 0 0.112701" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="front_mount" />
    </joint>

    <link name="rear_mount" />

    <joint name="rear_mount_joint" type="fixed">
        <origin xyz="-0.325 0 0.112701" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="rear_mount" />
    </joint>

    <!-- Additional definitions -->
    <xacro:include filename="$(arg urdf_extras)" />

    <!-- Gazebo definitions  -->
    <xacro:include filename="$(find coroco_description)/urdf/coroco.gazebo" />
</robot>